In [ ]:
numpy --> numerical + python

scipy --->

numpy --> numpy is basically use for multidimensional arrays and metrics


travis oliphant -  2005

release 1.0 version in 2006.

In [2]:
"1" + "1"

'11'

In [3]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
np.__version__

'2.2.6'

# 1 dimension

In [9]:
# convert list to array


my_list = [20,30,40,50]
print(my_list)
myarray = np.array(my_list)
myarray

[20, 30, 40, 50]


array([20, 30, 40, 50])

In [10]:
type(my_list)

list

In [11]:
type(myarray)

numpy.ndarray

In [12]:
np.array(range(1,6))

array([1, 2, 3, 4, 5])

# 2 dimension(2d)

In [13]:
d2 = np.array([[1,2],[3,4]])
d2

array([[1, 2],
       [3, 4]])

In [14]:
d2.shape

(2, 2)

In [15]:
type(d2)

numpy.ndarray

In [16]:
d2.ndim # to know the dimension

2

In [17]:
d2.nbytes

32

In [18]:
d2.size

4

In [19]:
d3 = np.array([[True, False],[False, True]])
d3

array([[ True, False],
       [False,  True]])

In [20]:
d3.shape

(2, 2)

# 3D

In [34]:
d3 = np.array([[[1,2],[3,4],[4,5]]])
d3

array([[[1, 2],
        [3, 4],
        [4, 5]]])

In [35]:
d3.ndim

3

In [36]:
d3.shape

(1, 3, 2)

# Array with random number



In [ ]:
# rand() --> generate a new number

In [40]:
np.random.rand()

0.13152334757433426

In [44]:
np.random.rand(3)

array([0.37674613, 0.63755376, 0.31668569])

In [46]:
np.random.rand(2,2)

array([[0.00324818, 0.01584879],
       [0.97827107, 0.86280402]])

In [48]:
# randint 

np.random.randint(2,100)

21

In [60]:
x = np.random.randint(2,10000,5)

In [61]:
x

array([8509, 9877, 5212, 4029, 3163], dtype=int32)

In [62]:
x.max()

np.int32(9877)

In [63]:
x.min()

np.int32(3163)

In [65]:
x.argmax()

np.int64(1)